Flag --validation has been deprecated, this arg is no longer used, all resources are validated using server-side apply dry-run
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-foundations
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-foundations
